@url_dev =http://localhost:3052/v1/api
POST {{url_dev}}/discount
Content-Type: application/json
x-api-key: 8e932132768802c8419c246f7f4eb05055f2997b7676628da0cbecec0104eb1475ad179e9cc31c4aaa106f9c4628c483310de37843b917381983a2f0719f6128
x-client-id: 680e0ac24987c6c686f99a34
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBlMGFjMjQ5ODdjNmM2ODZmOTlhMzQiLCJlbWFpbCI6InRlc3QxOEBnbWFpbC5jb20iLCJpYXQiOjE3NDc1NDc5OTAsImV4cCI6MTc0NzcyMDc5MH0.x07N96vvkM8lEdKd6qvZBGjNwH3NnGX3kqgETFnKWiU
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBlMGFjMjQ5ODdjNmM2ODZmOTlhMzQiLCJlbWFpbCI6InRlc3QxOEBnbWFpbC5jb20iLCJpYXQiOjE3NDc1NDc5OTAsImV4cCI6MTc0ODE1Mjc5MH0.z_d7q6Ygv9RmV0kvRKdVn6dMuqczZf66h9uKbdLmwP8

{
    "name": "ten percentage", 
    "description": "description",
    "type": "percentage",
    "value": 10,
    "max_value": 10,
    "code": "SHOP-1126",
    "start_date": "2023-04-15 09:00:00",
    "end_date": "2026-04-20 09:00:00",
    "max_uses": 100,
    "uses_count": 0,
    "users_used": [],
    "max_uses_per_user": 1,
    "min_order_value": 200000,
    "created_by": {},
    "is_active": true,
    "applies_to": "specific",
    "product_ids": ["682974145c0220da9fda9502"]
}

# {
#     "name": "name fixed amount", 
#     "description": "description",
#     "type": "percentage",
#     "value": 30000,
#     "max_value": 30000,
#     "code": "SHOP-11223",
#     "start_date": "2023-04-15 09:00:00",
#     "end_date": "2026-04-20 09:00:00",
#     "max_uses": 100,
#     "uses_count": 0,
#     "users_used": [],
#     "max_uses_per_user": 1,
#     "min_order_value": 200000,
#     "created_by": {},
#     "is_active": true,
#     "applies_to": "specific",
#     "product_ids": ["6818dae077802309ee1c1dc1", "6818da9877802309ee1c1db9"]
# }