@url_dev =http://localhost:3052/v1/api
GET {{url_dev}}/discount?shopId=680e0ac24987c6c686f99a34&limit=50&page=1
Content-Type: application/json
x-api-key: 8e932132768802c8419c246f7f4eb05055f2997b7676628da0cbecec0104eb1475ad179e9cc31c4aaa106f9c4628c483310de37843b917381983a2f0719f6128
x-client-id: 682974db5c0220da9fda9522
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODI5NzRkYjVjMDIyMGRhOWZkYTk1MjIiLCJlbWFpbCI6InRlc3QxOUBnbWFpbC5jb20iLCJpYXQiOjE3NDc1NDgyMDgsImV4cCI6MTc0NzcyMTAwOH0.keVgCEVdzyURTxqwZz1i0Ql0rwcL26pLRjSWjWrGcQw
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODI5NzRkYjVjMDIyMGRhOWZkYTk1MjIiLCJlbWFpbCI6InRlc3QxOUBnbWFpbC5jb20iLCJpYXQiOjE3NDc1NDgyMDgsImV4cCI6MTc0ODE1MzAwOH0.4ke1Y31UEJJOWHxp3q-e3oIWP13gpHTGgb2eCWnfceM
