services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-ecommerce
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db # Lưu dữ liệu vào folder local
    networks:
      - ecommerce-network

  redis:
    image: redis:7-alpine
    container_name: redis-ecommerce
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
