@url_dev =http://localhost:3052/v1/api
POST {{url_dev}}/product/publish/682975255c0220da9fda952a
Content-Type: application/json
x-api-key: 8e932132768802c8419c246f7f4eb05055f2997b7676628da0cbecec0104eb1475ad179e9cc31c4aaa106f9c4628c483310de37843b917381983a2f0719f6128
x-client-id: 682974db5c0220da9fda9522
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODI5NzRkYjVjMDIyMGRhOWZkYTk1MjIiLCJlbWFpbCI6InRlc3QxOUBnbWFpbC5jb20iLCJpYXQiOjE3NDc1NDczNzYsImV4cCI6MTc0NzcyMDE3Nn0.50par5UgIwWRGCY1dKyUxKolkMLUf9WL1icjmKeZwiE
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODI5NzRkYjVjMDIyMGRhOWZkYTk1MjIiLCJlbWFpbCI6InRlc3QxOUBnbWFpbC5jb20iLCJpYXQiOjE3NDc1NDczNzYsImV4cCI6MTc0ODE1MjE3Nn0.5cSVJ0vD1N0ifs_lr4tnhGoQDQEUS8QAtxh9iEsda4U
